version: '1'
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@dba1_high?TNS_ADMIN=/app/oracle_wallet
      - spring.datasource.username=FS2201_S8
      - spring.datasource.password=ActSum.S8_FS
    restart: always